import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Globe2, MapPin, MessageCircle, UsersRound } from 'lucide-react'
import { PageHero } from '@/components/shared/PageHero'
import { company } from '@/data/site'

export const metadata: Metadata = {
  title: 'About the Best Travel Agency in Kathmandu',
  description: 'Learn more about Good Luck International Travels & Tours, a trusted Kathmandu travel agency helping travellers plan flights, tours, hotels and visa support in Nepal and beyond.',
  alternates: { canonical: '/about' },
}

const hero='https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1800&q=88'
const team='/images/goodluckteam.png'
const planning='https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1500&q=88'

export default function About(){return <main><PageHero eyebrow="About Good Luck" title="Travel planning with a local team behind you." description="Good Luck International Travels & Tours helps travellers from Kathmandu arrange flights, hotels, holiday packages, visa support and experiences with practical guidance from enquiry to departure." image={hero} crumb="About Us" button="Talk to our team"/>
<section className="container-luxury py-20 sm:py-24"><div className="grid gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div><div className="section-kicker">Our story</div><h2 className="mt-3 text-4xl font-semibold leading-[.98] tracking-[-.06em] text-navy sm:text-6xl">A better trip starts with <span className="text-gradient">better planning.</span></h2><p className="mt-6 text-sm leading-7 text-muted">Good Luck is built around a simple idea: travel should feel exciting, while the planning behind it should feel clear. From Kathmandu, we help travellers understand their options, organise the important details and move forward with confidence.</p><p className="mt-4 text-sm leading-7 text-muted">Our work spans international and domestic flights, hotel reservations, holiday packages, visa assistance and travel support. We combine practical local knowledge with a service style that stays personal.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{[['Personal support','One conversation, one clear next step.'],['Practical planning','Routes, stays and documents organised around your trip.'],['Global reach','Travel ideas and arrangements across destinations worldwide.'],['Clear communication','Straightforward guidance before and during your journey.']].map(([t,d])=><div key={t} className="rounded-2xl border border-mist bg-white p-4"><CheckCircle2 size={17} className="text-sea"/><div className="mt-3 text-sm font-semibold text-navy-2">{t}</div><div className="mt-1 text-xs leading-5 text-muted">{d}</div></div>)}</div></div><div className="relative min-h-[520px] overflow-hidden rounded-[34px]"><Image src={team} alt="Travel team planning together" fill className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-navy/70 via-transparent to-transparent"/><div className="absolute bottom-6 left-6 right-6 rounded-[22px] border border-white/25 bg-white/12 p-5 text-white backdrop-blur-xl"><div className="text-[11px] font-semibold text-white/65">Good Luck travel desk</div><div className="mt-2 text-2xl font-semibold tracking-[-.03em]">Helping people turn travel plans into real journeys.</div></div></div></div></section>

<section className="bg-paper py-20 sm:py-24"><div className="container-luxury"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="relative mx-auto w-full max-w-[420px] overflow-hidden rounded-[32px] border-8 border-white bg-white shadow-[0_25px_70px_rgba(20,74,123,.13)]"><div className="relative aspect-[4/5]"><Image src="/images/aatif-aslam.png" alt="Aatif Aslam, Good Luck International Travels and Tours" fill className="object-cover object-top"/></div><div className="border-t border-cloud bg-white p-5"><div className="text-xl font-semibold text-navy">Aatif Aslam</div><div className="mt-1 text-xs font-semibold text-sea">Founder & Authorized Representative</div></div></div><div><div className="section-kicker">Meet the founder</div><h2 className="mt-3 text-4xl font-semibold leading-[.98] tracking-[-.06em] text-navy sm:text-6xl">Personal service is part of the <span className="text-gradient">promise.</span></h2><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-sea/20 bg-sea/5 px-3 py-2 text-sm font-medium text-navy"><span className="grid h-6 w-6 place-items-center rounded-full bg-sea text-[10px] font-bold text-white">5+</span> Years of travel experience</div><p className="mt-6 text-sm leading-7 text-muted">Aatif Aslam leads Good Luck with a service-first approach: listen carefully to what travellers need, explain the practical choices clearly and stay available when the details matter.</p><p className="mt-4 text-sm leading-7 text-muted">For travellers from Nepal, international travel can involve many moving pieces — flights, accommodation, documents, schedules and local arrangements. Our role is to make that process easier to understand and easier to manage.</p><div className="mt-7 flex flex-wrap gap-3"><a href="https://wa.me/9779816800052?text=Hello%20Aatif%2C%20I%20would%20like%20to%20discuss%20a%20travel%20plan." target="_blank" rel="noreferrer" className="btn-primary"><MessageCircle size={15}/> Speak on WhatsApp</a><Link href="/contact" className="btn-soft">Contact the team <ArrowRight size={14}/></Link></div></div></div></div></section>

<section className="container-luxury py-20 sm:py-24"><div className="grid gap-6 lg:grid-cols-2"><div className="relative min-h-[430px] overflow-hidden rounded-[30px]"><Image src={planning} alt="Travel planning and teamwork" fill className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-navy/70 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><div className="text-[11px] font-semibold text-white/65">One team, many journeys</div><div className="mt-2 max-w-md text-3xl font-semibold tracking-[-.04em]">From the first question to the final details.</div></div></div><div className="rounded-[30px] border border-mist bg-white p-7 sm:p-10"><div className="section-kicker">What we provide</div><h2 className="mt-3 text-4xl font-semibold tracking-[-.06em] text-navy">Travel services, connected.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{[['Flights','Domestic and international flight assistance.'],['Hotels','Stay options matched to your route and budget.'],['Holiday packages','Curated and tailored trips for different travel styles.'],['Visa assistance','Structured document and preparation guidance.'],['Transfers','Airport and local transfer arrangements where required.'],['Travel support','Human help when plans or questions change.']].map(([t,d],i)=><div key={t} className="rounded-2xl bg-paper p-4"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-cloud text-sea"><UsersRound size={14}/></span><div className="text-sm font-semibold text-navy-2">{t}</div></div><p className="mt-3 text-xs leading-5 text-muted">{d}</p></div>)}</div></div></div></section>

<section className="container-luxury pb-24"><div className="on-dark rounded-[30px] bg-gradient-to-br from-sea via-navy-2 to-navy px-7 py-10 text-white sm:px-12 sm:py-14"><div className="flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><div className="eyebrow text-white/60">Visit or message us</div><h2 className="mt-3 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Tinkune & Sinamangal, Kathmandu.</h2><div className="mt-4 flex flex-wrap gap-4 text-xs text-white/65"><span className="inline-flex items-center gap-2"><MapPin size={14}/> Tinkune, Kathmandu-32</span><span className="inline-flex items-center gap-2"><MapPin size={14}/> Sinamangal, Kathmandu</span><span className="inline-flex items-center gap-2"><Globe2 size={14}/> Nepal · Worldwide travel</span></div></div><a href="https://wa.me/9779816800052" target="_blank" rel="noreferrer" className="btn-gold"><MessageCircle size={16}/> WhatsApp Good Luck</a></div></div></section>
</main>}
